[Twitter Adapter] Add unit tests for ApplicationBuilderExtensions class
southworks/botbuilder-community-dotnet pull request #11
Opened 2020-09-16 16:02 UTC by sw-joelmut

## Description
This PR adds new xUnit test for the [ApplicationBuilderExtensions](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Twitter/ApplicationBuilderExtensions.cs#L10) class increasing its code coverage from **0%** to **86%**.

### Specific Changes
- Added the ApplicationBuilderExtensionsTests file with new unit test.

## Testing
The following images show the new tests passing and the resulting code coverage.
![image](https://user-images.githubusercontent.com/62260472/93362776-cc627a00-f81c-11ea-9984-c5d8629c8008.png)
![image](https://user-images.githubusercontent.com/62260472/93362782-cd93a700-f81c-11ea-8854-80b9cb6f85b1.png)

2020-09-16 17:24 UTC, denscollo approved these changes
LGTM

2020-09-16 18:43 UTC, ceciliaavila requested changes

2020-09-16 18:43 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Tests/ApplicationBuilderExtensionsTests.cs
> +using Microsoft.Extensions.Options;
Please, re-order these alphabetically. It's a linter rule that is not mandatory in this repo yet, but we could get ahead.

2020-09-16 18:43 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Tests/ApplicationBuilderExtensionsTests.cs
> +        private static readonly Mock<IOptions<TwitterOptions>> _testOptions = new Mock<IOptions<TwitterOptions>>();
Static properties should start with Uppercase.
```suggestion
        private static readonly Mock<IApplicationBuilder> TestApp = new Mock<IApplicationBuilder>();
        private static readonly Mock<IServiceProvider> TestService = new Mock<IServiceProvider>();
        private static readonly Mock<IOptions<TwitterOptions>> TestOptions = new Mock<IOptions<TwitterOptions>>();
```

2020-09-16 19:27 UTC, ceciliaavila approved these changes

2020-09-22 19:49 UTC, santgr11 approved these changes

2020-09-22 19:49 UTC, iscaltritti-sw approved these changes

2020-09-30 20:45 UTC, iscaltritti-sw approved these changes

2024-07-26 13:52 UTC, closed without merging