[Alexa Adapter] Add unit tests for AlexaRequestMapperOptions, MergedActivityResult and AlexaAttachmentContentTypes classes
southworks/botbuilder-community-dotnet pull request #17
Opened 2020-09-17 18:01 UTC by sw-joelmut

## Description
This PR adds tests for the following classes to increase code coverage.
- [AlexaRequestMapperOptions](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaRequestMapperOptions.cs#L5) increased from **83%** to **100%**.
- [MergedActivityResult](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Alexa.Core/MergedActivityResult.cs#L8) increased from **0%** to **100%**.
- [AlexaAttachmentContentTypes](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Alexa.Core/Attachments/AlexaAttachmentContentTypes.cs#L7) increased from **0%** to **100%**.

### Specific Changes
- Added the AlexaRequestMapperOptionsTests file with new unit test.
- Added the MergedActivityResultTests file with new unit test.
- Added the AlexaAttachmentContentTypesTests file with new unit test.

## Testing
The following images show the new tests passing and the resulting code coverage.
![image](https://user-images.githubusercontent.com/62260472/93505933-ea4dde80-f8f1-11ea-8357-ce00c8ee7b68.png)
![image](https://user-images.githubusercontent.com/62260472/93506063-15383280-f8f2-11ea-975e-f29b71636bab.png)

2020-09-17 20:50 UTC, ceciliaavila requested changes

2020-09-17 20:50 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Alexa.Tests/AlexaRequestMapperOptionsTests.cs
> +}
Maybe we can add a test to check the default values.

2020-09-18 12:23 UTC, ceciliaavila approved these changes

2020-09-22 19:43 UTC, santgr11 approved these changes

2020-09-22 19:47 UTC, iscaltritti-sw approved these changes

2020-09-30 20:43 UTC, iscaltritti-sw approved these changes

2024-07-26 13:53 UTC, closed without merging