[Alexa Adapter] Add unit tests for AlexaAuthorizationHandler class
southworks/botbuilder-community-dotnet pull request #19
Opened 2020-09-18 15:38 UTC by sw-joelmut

## Description
This PR adds tests for the [AlexaAuthorizationHandler](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaAuthorizationHandler.cs#L11) class increasing its code coverage from **0%** to **98%**.

### Specific Changes
- Added the AlexaAuthorizationHandlerTests file with new **xUnit** tests.

## Testing
The following images show the new tests passing and the resulting code coverage.
![image](https://user-images.githubusercontent.com/62260472/93616890-b20ad680-f9ab-11ea-8430-8f1367f6b8bf.png)
![image](https://user-images.githubusercontent.com/62260472/93616895-b3d49a00-f9ab-11ea-9378-ab881c593303.png)

2020-09-18 20:59 UTC, santgr11 approved these changes

2020-09-21 12:53 UTC, ceciliaavila requested changes

2020-09-21 12:53 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Alexa.Tests/AlexaAuthorizationHandlerTests.cs
> +            var result = alexaAuthorizationHandler.ValidateSkillId(null, null);
```suggestion
            var result = alexaAuthorizationHandler.ValidateSkillId(TestSkillRequest, null);
```

2020-09-21 14:24 UTC, ceciliaavila approved these changes

2020-09-22 19:44 UTC, iscaltritti-sw approved these changes

2024-07-26 13:53 UTC, closed without merging