[Alexa Adapter] Add unit tests for AlexaRequestMapper class
southworks/botbuilder-community-dotnet pull request #21
Opened 2020-09-21 14:15 UTC by sw-joelmut

## Description
This PR adds tests for the [AlexaRequestMapper](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaRequestMapper.cs#L22) class increasing its code coverage from **76%** to **99%**.

### Specific Changes
- Updated the [AlexaRequestMapperTests](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/tests/Bot.Builder.Community.Adapters.Alexa.Tests/AlexaRequestMapperTests.cs#L25) file with new **xUnit** tests.

## Testing
The following images show the new tests passing and the resulting code coverage.
![image](https://user-images.githubusercontent.com/62260472/93776459-ed024980-fbf9-11ea-8928-3a2224ebd003.png)
![image](https://user-images.githubusercontent.com/62260472/93776455-ea9fef80-fbf9-11ea-9a5c-b5728af35435.png)

2020-09-21 17:54 UTC, ceciliaavila requested changes

2020-09-21 17:54 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Alexa.Tests/AlexaRequestMapperTests.cs
> +
Please remove this extra line.

2020-09-21 17:54 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Alexa.Tests/AlexaRequestMapperTests.cs
> +
Same in here.

2020-09-21 19:03 UTC, ceciliaavila approved these changes

2020-09-21 19:03 UTC, sw-joelmut commented on tests/Bot.Builder.Community.Adapters.Alexa.Tests/AlexaRequestMapperTests.cs
> +
Those slippery empty lines, 👍.

2020-09-22 19:31 UTC, santgr11 approved these changes

2020-09-22 19:41 UTC, iscaltritti-sw requested changes
Inconsistent use of implicit/explicit constructor arguments.
Examples:
`new User()`
`new Intent`

2020-09-22 20:13 UTC, ceciliaavila commented
> Inconsistent use of implicit/explicit constructor arguments.
> Examples:
> `new User()`
> `new Intent`

2020-09-23 12:27 UTC, sw-joelmut commented
> 
> 
> Inconsistent use of implicit/explicit constructor arguments.
> Examples:
> `new User()`
> `new Intent`

It looks good to me, since we remove the explicit `()` when there are properties defined on the class instance, otherwise it should go the `()`. Maybe @ceciliaavila could provide more information on this, thanks.

2020-09-23 12:44 UTC, ceciliaavila commented
> > Inconsistent use of implicit/explicit constructor arguments.
> > Examples:
> > `new User()`
> > `new Intent`
> 
> It looks good to me, since we remove the explicit `()` when there are properties defined on the class instance, otherwise it should go the `()`. Maybe @ceciliaavila could provide more information on this, thanks.

Yes, Resharper suggests removing the `()` when you assign values to the properties in the instance.
![image](https://user-images.githubusercontent.com/44245136/94013156-0d5c1080-fd80-11ea-8e42-019ea144cfcf.png)

2020-09-28 17:37 UTC, iscaltritti-sw approved these changes

2024-07-26 13:53 UTC, closed without merging