[Twitter Adapter] Add unit tests for TwitterOptions class
southworks/botbuilder-community-dotnet pull request #4
Opened 2020-08-28 12:11 UTC by sw-joelmut

## Description
This PR add unit tests for the [TwitterOptions](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Twitter/TwitterOptions.cs#L9) class increasing its code coverage from **65%** to **100%**.

### Specific Changes
- Added the **TwitterOptionsTests** file with new unit tests.

## Testing
This image shows the new test passing and the resulting code coverage.
![image](https://user-images.githubusercontent.com/62260472/91559336-3f5b8d80-e90e-11ea-8ae2-c60e1a493976.png)

2020-08-28 13:09 UTC, ceciliaavila requested changes

2020-08-28 13:09 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Tests/TwitterOptionsTests.cs
> +﻿using System;
As this is a new file, I think we should include the Copyright header.

2020-08-28 13:09 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Tests/TwitterOptionsTests.cs
> +using System.Collections.Generic;
Remove the unnecessary usings.

2020-08-28 13:09 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Tests/TwitterOptionsTests.cs
> +        public async Task TwitterOptionsProperties()
Why is this method async?

2020-08-28 13:09 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Tests/TwitterOptionsTests.cs
> +        public async Task TwitterOptionsProperties()
```suggestion
        public Task TwitterOptionsPropertiesShouldBeSetSuccessfully()
```

2020-08-31 12:58 UTC, ceciliaavila requested changes

2020-08-31 12:58 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Tests/TwitterOptionsTests.cs
> +            Assert.AreEqual(true, options.IsValid);
```suggestion
            Assert.IsTrue(options.IsValid);
```

2020-08-31 12:58 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Tests/TwitterOptionsTests.cs
> +            Assert.AreEqual(true, options.AllowedUsernamesConfigured());
```suggestion
            Assert.IsTrue(options.AllowedUsernamesConfigured());
```

2020-08-31 13:08 UTC, ceciliaavila approved these changes

2020-09-22 20:03 UTC, santgr11 approved these changes

2020-09-30 20:47 UTC, iscaltritti-sw approved these changes

2024-07-26 13:52 UTC, closed without merging