[Twitter Adapter] Add unit tests for WebhooksEnterpriseManager class
southworks/botbuilder-community-dotnet pull request #5
Opened 2020-08-28 16:55 UTC by sw-joelmut

## Description
This PR add unit tests for the [WebhooksEnterpriseManager](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Twitter/Webhooks/Services/WebhooksEnterpriseManager.cs#L17) class increasing its code coverage from **14%** to **79%**.

### Specific Changes
- Updated the [WebhooksEnterpriseManagerTests](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/tests/Bot.Builder.Community.Adapters.Tests/Webhooks/Services/WebhooksEnterpriseManagerTests.cs#L12) file with new unit tests.

## Testing
The following images show the new test passing and the resulting code coverage.
![image](https://user-images.githubusercontent.com/62260472/91593126-fa4b5180-e935-11ea-9e15-2068ea3dd489.png)
![image](https://user-images.githubusercontent.com/62260472/91593133-fcadab80-e935-11ea-8b21-c88ad76c771e.png)

2020-08-31 13:06 UTC, ceciliaavila requested changes

2020-08-31 13:06 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Tests/Webhooks/Services/WebhooksEnterpriseManagerTests.cs
> +            var result = await enterpriseManager.RegisterWebhook("3");
Can we use a better fake URL here?

2020-08-31 13:06 UTC, ceciliaavila commented on tests/Bot.Builder.Community.Adapters.Tests/Webhooks/Services/WebhooksEnterpriseManagerTests.cs
> +            var result = await enterpriseManager.UnregisterWebhook("3");
The same in here.

2020-08-31 13:14 UTC, ceciliaavila approved these changes

2020-09-22 20:03 UTC, santgr11 requested changes

2020-09-22 20:03 UTC, santgr11 commented on tests/Bot.Builder.Community.Adapters.Tests/Webhooks/Services/WebhooksEnterpriseManagerTests.cs
> +
remove the space between var declarations

2020-09-22 20:03 UTC, santgr11 commented on tests/Bot.Builder.Community.Adapters.Tests/Webhooks/Services/WebhooksEnterpriseManagerTests.cs
> +
same here

2020-09-30 20:48 UTC, iscaltritti-sw approved these changes

2024-07-26 13:52 UTC, closed without merging