[Twitter Adapter] Add unit tests for WebhooksPremiumManager class
southworks/botbuilder-community-dotnet pull request #6
Opened 2020-08-28 18:17 UTC by sw-joelmut

## Description
This PR add unit tests for the [WebhooksPremiumManager ](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Twitter/Webhooks/Services/WebhooksPremiumManager.cs#L16) class increasing its code coverage from **14%** to **81%**.

### Specific Changes
- Updated the [WebhooksPremiumManagerTests](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/tests/Bot.Builder.Community.Adapters.Tests/Webhooks/Services/WebhooksPremiumManagerTests.cs#L12) file with new unit tests.

## Testing
The following images show the new tests passing and the resulting code coverage.
![image](https://user-images.githubusercontent.com/62260472/91596073-f5d56780-e93a-11ea-8394-c6564f67fc29.png)
![image](https://user-images.githubusercontent.com/62260472/91596077-f79f2b00-e93a-11ea-825f-6e7c6a32dcea.png)

2020-08-31 13:13 UTC, ceciliaavila submitted a review, later dismissed

2020-08-31 13:18 UTC, ceciliaavila approved these changes

2020-09-22 20:02 UTC, santgr11 requested changes

2020-09-22 20:02 UTC, santgr11 commented on tests/Bot.Builder.Community.Adapters.Tests/Webhooks/Services/WebhooksPremiumManagerTests.cs
> +
The should not be spaces between vars declarations

2020-09-22 20:02 UTC, santgr11 commented on tests/Bot.Builder.Community.Adapters.Tests/Webhooks/Services/WebhooksPremiumManagerTests.cs
> +            Assert.Equal(89, result.Error.Errors[0].Code);
same here, but the assert should be separated

2020-09-22 20:02 UTC, santgr11 commented on tests/Bot.Builder.Community.Adapters.Tests/Webhooks/Services/WebhooksPremiumManagerTests.cs
> +
same here

2020-09-30 20:48 UTC, iscaltritti-sw approved these changes

2024-07-26 13:52 UTC, closed without merging