[Twitter Adapter] Add unit tests for DirectMessageSender class
southworks/botbuilder-community-dotnet pull request #8
Opened 2020-09-15 17:47 UTC by sw-joelmut

## Description
This PR adds unit tests for the [DirectMessageSender](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Twitter/Webhooks/Services/DirectMessageSender.cs#L19) class increasing its code coverage from **23%** to **81%**.

### Specific Changes
- Updated the [DirectMessageSenderTests](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/tests/Bot.Builder.Community.Adapters.Tests/Webhooks/Services/DirectMessageSenderTests.cs#L13) file with new unit tests.

## Testing
The following images show the new tests passing and the resulting code coverage.
![image](https://user-images.githubusercontent.com/62260472/93245827-4681f880-f762-11ea-9b20-75e3e7aa50e2.png)
![image](https://user-images.githubusercontent.com/62260472/93245833-484bbc00-f762-11ea-9086-8aec6f1a76cf.png)

2020-09-15 17:56 UTC, santgr11 requested changes

2020-09-15 17:56 UTC, santgr11 commented on tests/Bot.Builder.Community.Adapters.Tests/Webhooks/Services/DirectMessageSenderTests.cs
> +
Remove the spaces between vars declarations

2020-09-15 17:56 UTC, santgr11 commented on tests/Bot.Builder.Community.Adapters.Tests/Webhooks/Services/DirectMessageSenderTests.cs
> +            var result = await sender.SendAsync(message);
same here

2020-09-15 18:00 UTC, santgr11 approved these changes

2020-09-15 18:40 UTC, ceciliaavila approved these changes

2020-09-22 19:50 UTC, iscaltritti-sw approved these changes

2024-07-26 13:53 UTC, closed without merging